---
title: "Set validation"
author: "Carmen Canedo"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

# Libraries
```{r, message=FALSE}
library(tidyverse)
```

# Validation set approach
## Simple Linear Regression
```{r}
n <- nrow(student_por)

Z <- sample(n, n / 2)

reg.fit <- lm(G3 ~ ., data = student_por, subset = Z)
```

```{r}
g3_predicted <- predict(reg.fit, student_por)
```

```{r}
plot(student_por$G3[-Z], g3_predicted[-Z], xlab = "Actual Grades", ylab = "Predicted Grades", main = "Prediction Accuracy of Full Linear Model")
abline(0,1)
```


```{r}
mean((student_por$G3 - g3_predicted)[-Z] ^ 2)
```

## Best Subset
```{r}
reg.bestsub <- lm(G3 ~ school + sex + address + Mjob + reason + guardian + traveltime + failures + schoolsup + higher + Dalc + health + absences + G1 + G2, data = student_por[Z])

g3_pred_bestsub <- predict(reg.bestsub, student_por)
```

```{r}
plot(student_por$G3[-Z], g3_pred_bestsub[-Z])
abline(0, 1)
```

```{r}
mean((student_por$G3 - g3_pred_bestsub)[-Z] ^ 2)
```


## Forwards
```{r}
summary(forward)

reg.forward <- lm(G3 ~ G2 + G1 + failures + reason + absences + sex + school + traveltime + health, data = student_por, subset = Z)

g3_pred_forward <- predict(reg.forward, student_por)
```

```{r}
plot(student_por$G3[-Z], g3_pred_forwards[-Z])
abline(0, 1)
```

```{r}
mean((student_por$G3 - g3_pred_forwards)[-Z] ^ 2)
```


## TESTING
```{r}
# null <- lm(G3 ~ 1, data = student_por)
# full <- lm(G3 ~ ., data = student_por)
# 
# forward <- step(null, scope = list(lower=null, upper = full), direction = "forward")
# 
# summary(forward)
```

```{r}
# backward <- step(full, scope = list(lower=null, upper = full), direction = "backward")
# 
# summary(backward)
```